name: Run custom pytest

on:
  push:

jobs:
  run-pytest:
    strategy:
      matrix:
        cloud-provider: [aws, azure, gcp]
        os:
          - image: ubuntu-latest
            id: lububuntu
          - image: windows-latest
            id: windows
          - image: macos-latest
            id: macos
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    name: Custom pytest on ${{ matrix.os.id }}-py${{ matrix.python-version }}
    runs-on: ${{ matrix.os.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup parameters file
        shell: bash
        env:
          PARAMETERS_SECRET: ${{ secrets.PARAMETERS_SECRET }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$PARAMETERS_SECRET" \
          .github/workflows/parameters/public/parameters_${{ matrix.cloud-provider }}.py.gpg > test/parameters.py

      - name: Install dependencies
        run: |
          python -m pip install ".[development,aio,secure-local-storage,pandas]"

      - name: Run pytest
        run: |
          pytest -vvv -k "overflow or down_scale" .
