name: Run custom pytest

on:
  push:

jobs:
  run-pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cloud-provider: [aws, azure, gcp]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup parameters file
        shell: bash
        env:
          PARAMETERS_SECRET: ${{ secrets.PARAMETERS_SECRET }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$PARAMETERS_SECRET" \
          .github/workflows/parameters/public/parameters_${{ matrix.cloud-provider }}.py.gpg > test/parameters.py

      - name: Install dependencies
        run: |
          python -m pip install ".[development,aio,secure-local-storage]"

      - name: Run pytest
        run: |
          pytest -vvv -k "file_permission" .
